[package]
name = "compute_skinning"
version = "0.1.0"
authors = ["AJ Weeks"]
edition = "2018"

[lib]
crate-type = ["lib", "dylib"]

[dependencies]
shared = { path = "../../shaders/shared" }
spirv-std = { path = "../../../crates/spirv-std", features = ["glam"] }
bytemuck = "1.7.0"
